name: pharmacy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.9.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_test: ^9.1.4
  equatable: ^2.0.5
  http: ^1.1.0
  animated_splash_screen: ^1.3.0
  photo_view: ^0.14.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.11
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  dio: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FEF5E6"
  adaptive_icon_foreground: "assets/icon/logo_fg.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/login.png
    - assets/register.png
    - assets/loading.json
